baseURL = '/'
languageCode = 'en-us'
title = 'Open Data Uganda'
theme='opu'

[menu]
  [[menu.main]]
    name = "Industries"
    url = ""
    weight = 1
    identifier = "industries"
    
    [[menu.main]]
      name = "Agriculture"
      url = "/tags/agriculture"
      parent = "industries"
      weight = 1
    [[menu.main]]
      name = "ICT"
      url = "/tags/ict"
      parent = "industries"
      weight = 2
    [[menu.main]]
      name = "Tourism"
      url = "/tags/tourism"
      parent = "industries"
      weight = 3
    [[menu.main]]
      name = "Manufacturing"
      url = "/tags/manufacturing"
      parent = "industries"
      weight = 4
    [[menu.main]]
      name = "Oil and Gas"
      url = "/tags/oil-and-gas"
      parent = "industries"
      weight = 5
    [[menu.main]]
      name = "Construction"
      url = "/tags/construction"
      parent = "industries"
      weight = 6
    [[menu.main]]
      name = "Fishing Industry"
      url = "/tags/fishing-industry"
      parent = "industries"
      weight = 7
    [[menu.main]]
      name = "Healthcare"
      url = "/tags/healthcare"
      parent = "industries"
      weight = 8

  [[menu.main]]
    name = "About Us"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Team"
    url = "/team"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 4

[params]
  paginate = 9

[permalinks]
  blog = "/blog/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
